services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-t-code-challenge}
    ports:
      - "${DOCKER_APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=3000
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-secret}@db:5432/${DB_NAME:-mydb}
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: ${APP_NAME:-t-code-challenge}-db
    ports:
      - "${DOCKER_DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_NAME:-mydb}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
