# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arrogance
service: t-code-challenge

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

plugins:
  - serverless-offline
  - serverless-express

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /{proxy+}
          method: any

custom:
  serverless-offline:
    httpPort: 3000
    host: '0.0.0.0'
    noPrependStageInUrl: true
